name: Build
on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        run: cmake .

      - name: Build
        run: cmake --build .

      - name: Extract Short Commit Hash
        id: extract
        shell: bash
        run: echo commit=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bsp_regen-windows-${{ steps.extract.outputs.commit }}
          path: |
            bin/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        run: cmake .

      - name: Build
        run: cmake --build .

      - name: Extract Short Commit Hash
        id: extract
        shell: bash
        run: echo commit=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bsp_regen-linux-${{ steps.extract.outputs.commit }}
          path: |
            bin/
